/* PRIZNANI K DANI Z PRIDANE HODNOTY (vzor cislo 11)
   vyznam parametru
     margin-left: odsazeni zleva od netisknutelne oblasti [mm]
     margin-top: odsazeni shora od netisknutelne oblasti [mm]
   poznamka: mente jen cisla pred jednotkou mm */

//************zmeny provedte zde*****************  //******puvodni hodnoty - nemente******
var dph11_1="margin-left: 15mm; margin-top: 0mm";  // "margin-left: 15mm; margin-top: 0mm";
var dph11_2="margin-left:  7mm; margin-top: 0mm";  // "margin-left:  7mm; margin-top: 0mm";
var dph11_3="margin-left: 15mm; margin-top: 0mm";  // "margin-left: 15mm; margin-top: 0mm";
var dph11_4="margin-left:  7mm; margin-top: 0mm";  // "margin-left:  7mm; margin-top: 0mm";


/* PRIZNANI K DANI Z PRIDANE HODNOTY (vzor cislo 10)
   vyznam parametru
     margin-left: odsazeni zleva od netisknutelne oblasti [mm]
     margin-top: odsazeni shora od netisknutelne oblasti [mm]
   poznamka: mente jen cisla pred jednotkou mm */

//************zmeny provedte zde*****************  //******puvodni hodnoty - nemente******
var dph10_1="margin-left: 15mm; margin-top: 0mm";  // "margin-left: 15mm; margin-top: 0mm";
var dph10_2="margin-left:  7mm; margin-top: 0mm";  // "margin-left:  7mm; margin-top: 0mm";


/* PRIZNANI K DANI Z PRIJMU TYP A (ZAMESTNANCI)
   vyznam parametru
     margin-left: odsazeni zleva od netisknutelne oblasti [mm]
     margin-top: odsazeni shora od netisknutelne oblasti [mm]
   poznamka: mente jen cisla pred jednotkou mm */

//************zmeny provedte zde*****************  //******puvodni hodnoty - nemente******
var dzp_a1="margin-left: 13mm; margin-top: 0mm";  // "margin-left: 13mm; margin-top: 0mm";
var dzp_a2="margin-left:  8mm; margin-top: 0mm";  // "margin-left:  8mm; margin-top: 0mm";
var dzp_a3="margin-left: 13mm; margin-top: 0mm";  // "margin-left: 13mm; margin-top: 0mm";
var dzp_a4="margin-left:  8mm; margin-top: 0mm";  // "margin-left:  8mm; margin-top: 0mm";


/* PRIZNANI K DANI Z PRIJMU TYP B (FYZICKE OSOBY)
   vyznam parametru
     margin-left: odsazeni zleva od netisknutelne oblasti [mm]
     margin-top: odsazeni shora od netisknutelne oblasti [mm]
   poznamka: mente jen cisla pred jednotkou mm */

//************zmeny provedte zde*****************  //******puvodni hodnoty - nemente******
var dzp_b1="margin-left: 13mm; margin-top: 0mm";  // "margin-left: 13mm; margin-top: 0mm";
var dzp_b2="margin-left:  8mm; margin-top: 0mm";  // "margin-left:  8mm; margin-top: 0mm";
var dzp_b3="margin-left: 13mm; margin-top: 0mm";  // "margin-left: 13mm; margin-top: 0mm";
var dzp_b4="margin-left:  8mm; margin-top: 0mm";  // "margin-left:  8mm; margin-top: 0mm";
var dzp_b5="margin-left: 13mm; margin-top: 0mm";  // "margin-left: 13mm; margin-top: 0mm";
var dzp_b6="margin-left:  8mm; margin-top: 0mm";  // "margin-left:  8mm; margin-top: 0mm";
var dzp_b7="margin-left: 13mm; margin-top: 0mm";  // "margin-left: 13mm; margin-top: 0mm";
var dzp_b8="margin-left:  8mm; margin-top: 0mm";  // "margin-left:  8mm; margin-top: 0mm";


/* PRIHLASKA ZAMESTNANCE K POJISTENI
   vyznam parametru
     margin-left: odsazeni zleva od netisknutelne oblasti [mm]
     margin-top: odsazeni shora od netisknutelne oblasti [mm]
   poznamka: mente jen cisla pred jednotkou mm */

//************zmeny provedte zde***************** //*******puvodni hodnoty - nemente***** 
var prihl_a1="margin-left: 3mm; margin-top: 0mm"; // "margin-left: 3mm; margin-top: 0mm";
var prihl_a2="margin-left: 6mm; margin-top: 0mm"; // "margin-left: 6mm; margin-top: 0mm";
var prihl_b1="margin-left: 3mm; margin-top: 0mm"; // "margin-left: 3mm; margin-top: 0mm";
var prihl_b2="margin-left: 6mm; margin-top: 0mm"; // "margin-left: 6mm; margin-top: 0mm";


/* ODHLASKA ZAMESTNANCE Z POJISTENI
   vyznam parametru
     margin-left: odsazeni zleva od netisknutelne oblasti [mm]
     margin-top: odsazeni shora od netisknutelne oblasti [mm]
   poznamka: mente jen cisla pred jednotkou mm */

//************zmeny provedte zde*****************  //*******puvodni hodnoty - nemente****
var odhl_a1="margin-left: 9mm; margin-top: 0mm";  // "margin-left: 9mm; margin-top: 0mm";
var odhl_a2="margin-left:25mm; margin-top:25mm";  // "margin-left:25mm; margin-top:25mm";
var odhl_b1="margin-left: 9mm; margin-top: 0mm";  // "margin-left: 9mm; margin-top: 0mm";


/* PREHLED O POJISTNEM
   vyznam parametru
     margin-left: odsazeni zleva od netisknutelne oblasti [mm]
     margin-top: odsazeni shora od netisknutelne oblasti [mm]
   poznamka: mente jen cisla pred jednotkou mm */

//************zmeny provedte zde*****************  //******puvodni hodnoty - nemente******
var prehl_a1="margin-left: 0mm; margin-top: 0mm";  // "margin-left: 0mm; margin-top: 0mm";
var prehl_a2="margin-left: 0mm; margin-top: 0mm";  // "margin-left: 0mm; margin-top: 0mm";
var prehl_b1="margin-left: 0mm; margin-top: 0mm";  // "margin-left: 0mm; margin-top: 0mm";
var prehl_b2="margin-left: 2mm; margin-top: 2mm";  // "margin-left: 2mm; margin-top: 2mm";


/* PREHLED PRO VZP ZA ROK 2000
   vyznam parametru
     margin-left: odsazeni zleva od netisknutelne oblasti [mm]
     margin-top: odsazeni shora od netisknutelne oblasti [mm]
   poznamka: mente jen cisla pred jednotkou mm */

//************zmeny provedte zde*****************  //******puvodni hodnoty - nemente******
var vzp1_00="margin-left:  9mm; margin-top: 0mm";  // "margin-left:  9mm; margin-top: 0mm";
var vzp2_00="margin-left:  4mm; margin-top: 6mm";  // "margin-left:  4mm; margin-top: 6mm";
var vzp3_00="margin-left:  9mm; margin-top: 6mm";  // "margin-left:  9mm; margin-top: 6mm";
var vzp4_00="margin-left:  8mm; margin-top: 0mm";  // "margin-left:  8mm; margin-top: 0mm";


/* PREHLED PRO OSSZ ZA ROK 2000
   vyznam parametru
     margin-left: odsazeni zleva od netisknutelne oblasti [mm]
     margin-top: odsazeni shora od netisknutelne oblasti [mm]
   poznamka: mente jen cisla pred jednotkou mm */

//************zmeny provedte zde*****************    //******puvodni hodnoty - nemente******
var ossz1_00="margin-left:  5mm; margin-top: 13mm";  // "margin-left:  5mm; margin-top: 13mm";
var ossz2_00="margin-left:  0mm; margin-top: 13mm";  // "margin-left:  0mm; margin-top: 13mm";
var ossz3_00="margin-left:  0mm; margin-top: 13mm";  // "margin-left:  0mm; margin-top: 13mm";
var ossz4_00="margin-left:  7mm; margin-top: 13mm";  // "margin-left:  7mm; margin-top: 13mm";
